#!/usr/bin/python 

# Worker state constant
WORKER_UNKNOW_STATE = 0
WORKER_FREE_STATE = 1
WORKER_NORMAL_STATE = 2
WORKER_CONGESTED_STATE = 3
WORKER_EMERGENCY_STATE = 4

# Order constant
ORDER_DO = 0
RODER_MOD = 1


